version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - casehelpsvp-network
    env_file: ./.env
    environment:
      - MYSQL_ROOT_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db:/var/lib/mysql
  backend:
    container_name: backend
    depends_on:
      - mysqldb
    build: 
      context: ./backend
    restart: always
    env_file: ./.env
    ports:
      - 443:443
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
    stdin_open: true
    tty: true
    networks:
      - casehelpsvp-network
    volumes:
     - /app/node_modules
     - ./backend:/app
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - casehelpsvp-network
    volumes:
     - /app/node_modules
     - ./frontend:/app

networks: 
  casehelpsvp-network:

volumes: 
  db: