import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lar São Vicente de Paula</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Lar São Vicente de Paula
        </h1>

        <p className={styles.description}>
          Página Principal
        </p>
      </main>

      <footer className={styles.footer}>
        Powered by Time de desenvolvimento do CaseHelpSVP
      </footer>
    </div>
  )
}
